### ISSUE TITLE
[Bug] Type of Step

### ISSUE THREAD

**Issue by amcdnl** [use-wizard/use-wizard#2]
I'm curious why the typescript type of a step is `ReactText`. Seems like it should be `step: number | string`.

**Comment by ezrafayet** [comment]
By digging into the React types I found out: 

`type ReactText = string | number;`

I will leave this issue opened so I can work on types better.

**Comment by ezrafayet** [comment]
I confirm ReactText is an alias for string | number. 
It defines what types can be printed out as texts in React.
