### ISSUE TITLE
[Docs] Show implementation Example

### ISSUE THREAD

**Issue by amcdnl** [use-wizard/use-wizard#3]
I was able to figure it out but it might be ideal to show a basic implementation of how to use the lib. I made a couple basic mistakes that could be easily mitigated with that.

**Comment by ezrafayet** [comment]
I was considering to write a medium article about it (maybe when next version is released).

Before that I will add better examples in the doc as you say, and I will add three simple react pages to the repo that provides examples of the three different use cases (They would be HTML file using react through the CDN, they would not be full react projects of course).

On our platform we have many multi-paths wizards that changes a lot (they are automatically generated, and we also change the static ones a lot), I will provide an example on how to build a wizard that can be really easy to maintain and modify, don't hesitate to give me your advice on that.

**Comment by amcdnl** [comment]
I would recommend using codesandbox.io over a whole react project in a git repo like that.

**Comment by ezrafayet** [comment]
Just tried it, it is incredibly effective indeed, I will include examples in the next deploy on sunday.

**Comment by amcdnl** [comment]
You can automate them too - like w/ a github action.

**Comment by ezrafayet** [comment]
A first implementation example was released (the link in the README.md). Three more will follow during the week (including one for the nested wizard and one for the conditional steps).
