### ISSUE TITLE
Need Nested Wizard implementation or documentation

### ISSUE THREAD

**Issue by mrrohit1** [use-wizard/use-wizard#4]
Nested wizard implementation seems to be confusing, Please provide documentation

**Comment by ezrafayet** [comment]
Hi,

Did you see the first implementation example ? https://codesandbox.io/s/use-wizard-2-q243g

I need to provide two more, I'll try to do so soon

**Comment by bayareacoder** [comment]
Interesting hook but the documentation is lacking for what makes this interesting, which is the multi-path feature. Pls show which commands are needed to step through your non-linear example.

I looked at your test code below. How do you specify the next step based on the user selecting "1" or "2" in state "c"? Why does it follow path 1 necessarily?

```
test("Complex wizard from string to next nested position (follows path 1)", () => {

  const a = getNextStep("c", ["a", "b", "c", {
    "1": ["d", "e", "f"],
    "2": ["g", "h"],
  }, "i"]);
  expect(a).toBe("d");
});
```

Looking more at your code, I think I get it now. Based on user decision in state "c", you need to do `wizard.goToStep("d")` or `wizard.gotoStep("g")`, and from there `nextStep()` and `previousStep()` will work again, correct?

**Comment by reuben-thundergrid** [comment]
would be nice to see the nested example if this is still being maintained. The only npm package that has this feature from what I can find

**Comment by ezrafayet** [comment]
Hey @reuben-thundergrid, I will add this in the readme in a few days if it is still relevant for you ! (I failed to find time last time I tried, but I see it is being used twice as much as it used to so I will provide this kind of doc)

**Comment by ezrafayet** [comment]
I have added a live demo of various types of wizards:
[https://ezrafayet.com/use-wizard/live-demo-v4/](https://ezrafayet.com/use-wizard/live-demo-v4/)

And you can find the code of all the wizards on a branch here:
[https://github.com/ezrafayet/use-wizard/tree/v5/packages/examples-v4/src/pages](https://github.com/ezrafayet/use-wizard/tree/v5/packages/examples-v4/src/pages)

Note the latest version is stable (and used in production), but I will start working on the version 5 that will bring many improvements. If you have any other questions, requests or anything feel free to open another issue.
